all: exercise1 exercise2 exercise3 exercise4 exercise5

exercise1: exercise1.c
	gcc -o exercise1 exercise1.c -Wall -Wextra -pedantic

exercise2: exercise2.c
	gcc -o exercise2 exercise2.c -Wall -Wextra -pedantic

exercise3: exercise3.c
	gcc -o exercise3 exercise3.c -Wall -Wextra -pedantic	

exercise4: exercise4.c
	gcc -o exercise4 exercise4.c -O3 -Wall 	

exercise5: exercise5.c
	gcc -o exercise5 exercise5.c -Wall -Wextra -pedantic