all: exercise2 exercise3 exercise4 exercise5

exercise: exercise2.c
	gcc -o exercise2 exercise2.c -Wall -Wextra -pedantic -lm

exercise3: exercise3.c
	gcc -o exercise3 exercise3.c -Wall -Wextra -pedantic

exercise3: exercise4.c
	gcc -o exercise4 exercise4.c -Wall -Wextra -pedantic

exercise3: exercise5.c
	gcc -o exercise5 exercise5.c -Wall -Wextra -pedantic
